#!/bin/sh

echo "커밋 메세지 형식 확인 중입니다"

commit_template_file=$(git config commit.template)

if [ -z "$commit_template_file" ]; then
  echo "커밋 템플릿이 구성되어 있지 않습니다. 커밋 템플릿 설정을 해주세요. git config --local commit.template .github/commit_template.txt"
  exit 1
fi

commit_msg_file="$1"
commit_msg_type="$2"
commit_msg="$3"

if [ "$commit_msg_type" = "-m" ]; then
  echo "$commit_msg" > "$commit_msg_file"
fi

commit_msg=$(cat "$commit_msg_file")

commit_msg_regex=$(cat "$(dirname "$0")/../../.github/commit_regular.txt")

if ! echo "$commit_msg" | grep -Eq "$commit_msg_regex"; then
  echo "유효하지 않은 커밋 메시지 형식입니다."
  echo
  cat "$commit_template_file"
  echo
  exit 1
fi