#!/bin/sh

echo "커밋 메세지 형식 확인 hook이 실행 중입니다"

default_commit_template=".github/commit_template.txt"

commit_template_file=$(git config --local --get commit.template)

if [ -z "$commit_template_file" ]; then
  echo "로컬로 설정된 커밋 템플릿이 없습니다. 기본 커밋 템플릿을 설정합니다."
  git config --local commit.template "$default_commit_template"
  commit_template_file="$default_commit_template"
fi

commit_msg_file="$1"
commit_msg_type="$2"
commit_msg="$3"

if [ "$commit_msg_type" = "-m" ]; then
  echo "$commit_msg" > "$commit_msg_file"
fi

commit_msg=$(cat "$commit_msg_file")

commit_msg_regex=$(cat "$(dirname "$0")/../../.github/commit_regular.txt")

if ! echo "$commit_msg" | grep -Eq "$commit_msg_regex"; then
  echo "유효하지 않은 커밋 메시지 형식입니다."
  echo
  cat "$commit_template_file"
  echo
  exit 1
fi

echo "커밋 메시지 형식이 유효합니다."