name: server build test (Github Actions)

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
      KAKAO_REDIRECT_URL: ${{ secrets.KAKAO_REDIRECT_URL }}
      KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
    
    steps:
      - name: ✔️ 리포지토리 가져오기
        uses: actions/checkout@v4

      - name: ✔️ JDK 17 설치
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ✔️ Gradle 명령 실행 권한 설정
        run: chmod +x gradlew

      - name: ✔️ Gradle build
        run: ./gradlew build -x installLocalGitHook -x test -x spotlessJava -x spotlessJavaApply -x spotlessJavaCheck -x spotlessMisc -x spotlessMiscApply -x spotlessMiscCheck -x spotlessCheck -x spotlessApply

      - name: ✔️ Gradle test
        run: ./gradlew --info test -Dspring.profiles.active=test