name: 커밋 메시지 확인

on: [ push ]

jobs:
  commit_message_check:
    runs-on: ubuntu-latest

    steps:
      - name: ✔ 리포지토리 가져오기
        uses: actions/checkout@v4

      - name: ✔ 커밋 메시지 정규표현식 읽기
        id: read_commit_regex
        run: |
          commit_msg_regex=$(cat ./.github/commit_regular.txt)
          echo "커밋 메시지 정규 표현식: $commit_msg_regex"
          echo "::set-output name=commit_regex::$commit_msg_regex"

      - name: ✔ 커밋 메시지 확인하기
        run: |
          commit_msg=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "커밋 메시지: $commit_msg"
          commit_regex="${{ steps.read_commit_regex.outputs.commit_regex }}"
          if [[ ! "$commit_msg" =~ $commit_regex ]]; then
            echo "유효하지 않은 커밋 메시지 형식입니다."
            exit 1
          else
            echo "커밋 메시지가 유효합니다."
          fi
